<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>tr.alperendemir</groupId>
  <artifactId>lifesteal</artifactId>
  <version>1.0.2</version>
  <packaging>jar</packaging>

  <name>lifesteal</name>

  <properties>
    <java.version>25</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <finalName>${project.name}-${project.version}</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.2</version>
          <configuration>
              <outputFile>${project.build.directory}/${project.name}-${project.version}.jar</outputFile>
              <filters>
                  <filter>
                      <artifact>*:*</artifact>
                      <excludes>
                          <exclude>module-info.class</exclude>
                          <exclude>META-INF/versions/**/module-info.class</exclude>
                          <exclude>META-INF/MANIFEST.MF</exclude>
                      </excludes>
                  </filter>
              </filters>
              <relocations>
                  <relocation>
                      <pattern>org.bstats</pattern>
                      <shadedPattern>tr.alperendemir.lssmp.bstats</shadedPattern>
                  </relocation>
              </relocations>
          </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>

  <repositories>
      <repository>
          <id>spigotmc-repo</id>
          <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
      </repository>
      <repository>
          <id>sonatype</id>
          <url>https://oss.sonatype.org/content/groups/public/</url>
      </repository>
      <repository>
          <id>mojang-libraries</id>
          <url>https://libraries.minecraft.net/</url>
      </repository>
  </repositories>

  <dependencies>
      <dependency>
          <groupId>org.spigotmc</groupId>
          <artifactId>spigot-api</artifactId>
          <version>26.2-R0.1-SNAPSHOT</version>
          <scope>provided</scope>
      </dependency>
      <dependency>
          <groupId>com.google.code.gson</groupId>
          <artifactId>gson</artifactId>
          <version>2.10.1</version>
      </dependency>
      <dependency>
          <groupId>com.mojang</groupId>
          <artifactId>brigadier</artifactId>
          <version>1.0.18</version>
      </dependency>
      <dependency>
          <groupId>info.debatty</groupId>
          <artifactId>java-string-similarity</artifactId>
          <version>2.0.0</version>
      </dependency>
      <dependency>
          <groupId>org.jetbrains</groupId>
          <artifactId>annotations</artifactId>
          <version>26.1.0</version>
      </dependency>
      <dependency>
          <groupId>org.hsqldb</groupId>
          <artifactId>hsqldb</artifactId>
          <version>2.7.3</version>
      </dependency>

      <dependency>
          <groupId>org.bstats</groupId>
          <artifactId>bstats-bukkit</artifactId>
          <version>3.2.1</version>
          <scope>compile</scope>
      </dependency>
  </dependencies>
</project>
